import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------------
# PAGE CONFIG
# ------------------------------------------------
st.set_page_config(
    page_title="Call Center Performance Dashboard",
    page_icon="📞",
    layout="wide"
)

# ------------------------------------------------
# LOAD DATA
# ------------------------------------------------
df = pd.read_csv("Cleaned_Data.csv")

# ------------------------------------------------
# COMPANY HEADER
# ------------------------------------------------

st.markdown(
    """
    <h1 style='text-align:center; color:#0E4C92;'>
        🎧 ConnectCare Call Center
    </h1>
    <h3 style='text-align:center; color:gray;'>
        Customer Service Performance Dashboard
    </h3>
    """,
    unsafe_allow_html=True
)
# ------------------------------------------------
# CREATE MONTH COLUMN
# ------------------------------------------------
df["Date of Call"] = pd.to_datetime(df["Date of Call"])
df["Month"] = df["Date of Call"].dt.month_name()

# ------------------------------------------------
# KPI SECTION
# ------------------------------------------------
total_calls = df["Call number"].count()

total_purchase = df["Purchase"].sum()

avg_rating = df["Rating"].mean()

total_customers = df["Customer ID"].nunique()

k1, k2, k3, k4 = st.columns(4)

k1.metric("📞 Total Calls", f"{total_calls:,}")
k2.metric("💰 Total Purchase", f"${total_purchase:,.0f}")
k3.metric("⭐ Avg Rating", f"{avg_rating:.2f}")
k4.metric("👥 Customers", f"{total_customers:,}")

st.divider()

# =====================================================
# ROW 1
# =====================================================

c1, c2 = st.columns(2)

with c1:

    monthly_calls = df.groupby("Month")["Call number"].count()

    fig, ax = plt.subplots(figsize=(7,4))
    monthly_calls.plot(kind="line", marker="o", ax=ax)

    ax.set_title("Monthly Call Volume")
    ax.set_ylabel("Number of Calls")

    st.pyplot(fig)

with c2:

    rep_calls = (
        df.groupby("Representative")["Call number"]
        .count()
        .sort_values(ascending=False)
    )

    fig, ax = plt.subplots(figsize=(7,4))
    rep_calls.plot(kind="bar", ax=ax)

    ax.set_title("Representative Call Volume")
    ax.set_ylabel("Calls")

    st.pyplot(fig)

# =====================================================
# ROW 2
# =====================================================

c3, c4 = st.columns(2)

with c3:

    fig, ax = plt.subplots(figsize=(6,5))

    rep_counts = df["Representative"].value_counts().head(5)

    ax.pie(
        rep_counts,
        labels=rep_counts.index,
        autopct="%1.1f%%",
        startangle=90,
        shadow=True,
        wedgeprops={"edgecolor":"white"}
    )

    ax.set_title("Top 5 Representatives by Calls")
    ax.set_ylabel("")

    st.pyplot(fig)
with c4:

    avg_rep_rating = (
        df.groupby("Representative")["Rating"]
        .mean()
        .sort_values(ascending=False)
    )

    fig, ax = plt.subplots(figsize=(7,4))
    avg_rep_rating.plot(kind="bar", ax=ax)

    ax.set_title("Average Rating by Representative")
    ax.set_ylabel("Average Rating")

    st.pyplot(fig)

# =====================================================
# ROW 3
# =====================================================

c5, c6 = st.columns(2)

with c5:

    fig, ax = plt.subplots(figsize=(7,4))

    ax.scatter(
        df["Duration"],
        df["Purchase"],
        alpha=0.6
    )

    ax.set_title("Call Duration vs Purchase")
    ax.set_xlabel("Call Duration")
    ax.set_ylabel("Purchase Amount")

    st.pyplot(fig)

with c6:

    customer_purchase = (
        df.groupby("Customer ID")["Purchase"]
        .sum()
        .sort_values(ascending=False)
        .head(10)
    )

    fig, ax = plt.subplots(figsize=(7,4))

    customer_purchase.plot(
        kind="bar",
        ax=ax
    )

    ax.set_title("Top 10 Customers by Purchase")
    ax.set_ylabel("Purchase Amount")

    st.pyplot(fig)

# =====================================================
# ROW 4
# =====================================================

c7, c8 = st.columns(2)

with c7:

    rep_purchase = (
        df.groupby("Representative")["Purchase"]
        .sum()
        .sort_values(ascending=False)
    )

    fig, ax = plt.subplots(figsize=(7,4))
    rep_purchase.plot(kind="bar", ax=ax)

    ax.set_title("Purchase Generated by Representative")
    ax.set_ylabel("Purchase")

    st.pyplot(fig)

with c8:

    monthly_purchase = (
        df.groupby("Month")["Purchase"]
        .sum()
    )

    fig, ax = plt.subplots(figsize=(7,4))

    monthly_purchase.plot(
        kind="line",
        marker="o",
        ax=ax
    )

    ax.set_title("Monthly Purchase Trend")
    ax.set_ylabel("Purchase Amount")
    ax.set_xlabel("Month")

    st.pyplot(fig)

st.divider()

st.success("Call Center Performance Dashboard Ready")

st.markdown("---")
st.subheader("📋 Raw Data")

st.dataframe(df, use_container_width=True)

st.markdown("---")
st.subheader("💡 Business Recommendations")

st.markdown("""
- Improve training for representatives whose average customer ratings are below the team average.
- Reduce average call duration while maintaining high customer satisfaction.
- Analyze low-purchase calls and refine sales scripts to improve conversion.
- Increase staffing during months with higher call volume.
- Recognize and reward top-performing representatives based on ratings and purchase generation.
""")